### ISSUE TITLE
How to configure the play-autosource 2.0 dependency in play 2.3.x

### ISSUE THREAD

**Issue by sidthesloth** [mandubian/play-autosource#47]
Hi

How do I configure the play-autosource 2.0 dependency in play 2.3.x?

this is what I've tried in build.sbt and i get errors below

name := "tester"

version := "1.0"

lazy val `tester` = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq( "play-autosource" %% "reactivemongo" % "2.0-SNAPSHOT" )

resolvers += "Mandubian repository snapshots" at "https://github.com/mandubian/m..."

resolvers += "Mandubian repository releases" at "https://github.com/mandubian/m..."

resolvers += "Sonatype Snapshots" at "http://oss.sonatype.org/conten..."

unmanagedResourceDirectories in Test <+= baseDirectory ( _ /"target/web/public/test" )

ERRORS
[info] Resolving org.scala-lang#scala-compiler;2.11.1 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
[info] Resolving jline#jline;2.11 ...
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: UNRESOLVED DEPENDENCIES ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: play-autosource#reactivemongo_2.11;2.0-SNAPSHOT: not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: play-autosource#reactivemongo_2.11;2.0-SNAPSHOT: not found

**Comment by loicdescotte** [comment]
@sidthesloth You can clone the repo and then run `sbt publish-local` to get a version compatible with scala 2.11 in your local ivy repository

**Comment by sidthesloth** [comment]
@loic Descotte

Thank you for that will try it out.

**Comment by PovilasID** [comment]
@loicdescotte Thanks for the tip but did not help me still get the same error

**Comment by taylorsmithgg** [comment]
My forked repo has fixes in place for compatibility with Play 2.3.X: 
https://github.com/taylorsmithgg/play-autosource
62a50c0dded447589250537bca3d2a134372ad5e

**Comment by mandubian** [comment]
nice that you go on using & developing this project ;)

**Comment by taylorsmithgg** [comment]
I stumbled across it the other day and couldn't help but check it out. Kudos on your work!

**Comment by sidthesloth** [comment]
Hi,

I followed @Loic's suggestion and cloned the repo then run sbt publish
local and everything worked out perfectly. Will try your fork @Taylor
thanks for sharing.
